const ACTION_TYPES = {
 'SIGN_IN': 'SIGN_IN',
 'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
 'SIGN_IN_ERROR': 'SIGN_IN_ERROR'
};

export const USERS_TYPES = {
  'GET_USERS_LIST': 'GET_USERS_LIST',
  'GET_USERS_LIST_SUCCESS': 'GET_USERS_LIST_SUCCESS',
  'GET_USERS_LIST_ERROR': 'GET_USERS_LIST_ERROR',
  'GET_USER': 'GET_USER',
  'GET_USER_SUCCESS': 'GET_USER_SUCCESS',
  'GET_USER_ERROR': 'GET_USER_ERROR',
  'DELETE_USER': 'DELETE_USER',
  'DELETE_USER_SUCCESS': 'DELETE_USER_SUCCESS',
  'DELETE_USER_ERROR': 'DELETE_USER_ERROR',
};

export default ACTION_TYPES;
